### ISSUE TITLE
Selecting a colour shows outline on :focus 

### ISSUE THREAD

**Issue by darylknight** [Rias500/craft-colour-swatches#11]
Selecting a colour in Chrome shows a blue outline around the colour.

![image](https://user-images.githubusercontent.com/1250017/41100294-a18bed22-6a69-11e8-9d2d-f9a07a50c10e.png)

Could be fixed with 
`.color-swatches button {
    outline: none;
}`

**Comment by Rias500** [comment]
Fixed in 1.1.4, thanks for reporting!
