### ISSUE TITLE
Trying to access hex in plugin

### ISSUE THREAD

**Issue by howells** [Rias500/craft-colour-swatches#14]
Hi - I'm trying to access the value of the colour swatch in a custom plugin but everything in the ColorData Object seems to be private so I can't get the value. Is there any way I can do this?

**Comment by Rias500** [comment]
There's no ColorData object in this plugin. I assume you're using the Craft CMS default color field, then you can use the methods in this class https://github.com/craftcms/cms/blob/e916d854d869d55de286c0e2ffe5f4e1161d8219/src/fields/data/ColorData.php

So for hex that would just be `getHex()`

**Comment by howells** [comment]
Wow I'm truly stupid sometimes. So sorry!
