### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by christopherdowson-contrast** [Rias500/craft-colour-swatches#15]
Is there any plan for a config file? Being able to configure preset colour lists would be an absolute lifesaver and much more DRY.

**Comment by Rias500** [comment]
Currently not possible to preset colour lists, it's not something I personally need but you can always send a PR to add this and I'll happily merge it

**Comment by christopherdowson-contrast** [comment]
I have no idea how to do that, but I'll look into it.

**Comment by Rias500** [comment]
I've had some time and added this in 1.2.0, let me know if everything works as you'd like https://github.com/Rias500/craft-colour-swatches#using-the-config-file

**Comment by christopherdowson-contrast** [comment]
Oh brilliant. Thank you! I'll go check it out now 👍
