### ISSUE TITLE
Must use {{ fieldName.value.value.color }} to access property

### ISSUE THREAD

**Issue by TimothyLoyer** [Rias500/craft-colour-swatches#2]
I believe this is because the JSON the model constructor gets already contains a value key. I believe accessing this key when you store it on the public class property will fix this so the magic method can access the properties in $this->value properly.

`    public function __construct($value)
    {
        $this->value = json_decode($value).value;
    }
`

**Comment by Rias500** [comment]
Thanks for reporting this!

**Comment by TimothyLoyer** [comment]
No problem- but it ends up I've given you bad advice as this has had a negative effect. When you try to edit an entry with this field now, it breaks because it cannot find ->value. I'm not entirely sure how and when Craft is invoking your models, or what the data going into it looks like- so I'm not sure how to help though.

**Comment by Rias500** [comment]
@TimothyLoyer Went through the full plugin and changed some things to fix this at the core now, try the new release and let me know if everything runs as expected! :)
