### ISSUE TITLE
Color definition in config file occurs an error => not countable() 

### ISSUE THREAD

**Issue by TomHell** [Rias500/craft-colour-swatches#24]
Create config/colour-swatches.php and set custom color occurs a in CraftCMS Backend while editing the field settings again.

**Error**
count(): Parameter must be an array or an object that implements Countable

**Reproduce**
1. Create  config file like in the example, 
2. Create new field in CraftCMS Backend (activate lightswitch => Use config options)
3. Save and go back to edit the field again occurs the error like in the title

=> Can someone confirm that?

**Naming convention of config file**
You use 
> config/colour-swatches.php (use in Tutorial)
 and
> config/color-swatches.php (this might be wrong but written as comment in the example config file)

Which is correct or even better?

**Comment by benface** [comment]
I fixed this in #23. @Rias500 any chance it can be merged in soon? :)

**Comment by Rias500** [comment]
Merged and released, thanks!
