### ISSUE TITLE
craft-colour-drops

### ISSUE THREAD

**Issue by H-i-red** [Rias500/craft-colour-swatches#4]
Hi man,

Great plugin!
Any chance for a craft-colour-drops plugin ? ;)
![colorme](https://user-images.githubusercontent.com/19476159/35380350-4f7aafaa-01b9-11e8-9700-70d28844a739.jpg)
Perhaps using checkboxes instead of radiobuttons, to let user select one or more colors..
Best regards /

Fredrik

**Comment by Rias500** [comment]
If I understand correctly you'd like it to be a dropdown instead of how it looks now?

**Comment by H-i-red** [comment]
Hi, no, I was thinking of a new plugin called **craft-colour-drops.** I like this one with swatches. I actually hacked your plugin and added a simple js file, changed some css, and I have a drop down...; )But It would be super nice to have it as plugin instead..

**Comment by Rias500** [comment]
You can always create a plugin out of it! Nothing is stopping you ;)

**Comment by H-i-red** [comment]
Was waiting for that answer lol.. o well, here I go... launch date this year if everything goes alright..haha

**Comment by Rias500** [comment]
Good luck 😀
