### ISSUE TITLE
PHP error when saving as a draft

### ISSUE THREAD

**Issue by tyler-deboer** [Rias500/craft-colour-swatches#5]
Repro: I have an entry with a matrix field that includes a Colour Swatch block.  When I try saving an entry as a draft, I get an error.

```
PHP Warning – yii\base\ErrorException
json_decode() expects parameter 1 to be string, array given
```

The stack trace tells me that it's related to [line 20](https://github.com/Rias500/craft-colour-swatches/blob/master/src/models/ColourSwatches.php#L20) in `/src/models/ColourSwatches.php`

**Comment by Rias500** [comment]
This should be fixed in the new release, let me know if you have any other issues!
