### ISSUE TITLE
Breaks craft when changing existing fields to colour swatch field type

### ISSUE THREAD

**Issue by wormmoon** [Rias500/craft-colour-swatches#6]
Hello,

I'm currently using radio buttons to select a colour option, but when I change that field type to the colour swatch field type it breaks the admin side and the front end of any page that contains that field. Here's the error: 

PHP Notice – yii\base\ErrorException
Trying to get property of non-object

The plug in also doesn't warn you there will be data loss in this case even though all data is lost when changing the field type.

The plug in works if I delete the field and completely recreate it from new.

**Comment by Rias500** [comment]
Hi @wormmoon 

Craft clearly warns that there might be data loss when switching the type of the field:

<img width="296" alt="afbeelding" src="https://user-images.githubusercontent.com/3626559/37567526-9f9d6de6-2ac8-11e8-8486-4a14662f11c7.png">

If you want to be able to change from radio buttons to the plugin, you could write a [Content Migration](https://github.com/craftcms/docs/blob/v3/en/content-migrations.md) to handle this for you programmatically. This plugin cannot account for all possible use cases or migrations that might be possible.
