### ISSUE TITLE
RGBA instead of Hex

### ISSUE THREAD

**Issue by CreateSean** [Rias500/craft-colour-swatches#7]
I would love to see an option to have colors with RGBA instead of hex. This way the client could choose from different levels of transparency on a single color.

i.e.

rgb(147, 147, 147)
rgba(147, 147, 147, 0.8)
rgba(147, 147, 147, 0.6)
rgba(147, 147, 147, 0.4)

So 4 different grey's where they can choose the transparency as needed.

**Comment by Rias500** [comment]
Actually ran into this today too :) Fixed in the new release! You can now use `;` as a delimiter which takes presedence over `,` so you should be able to defined rgba colours in there now!

**Comment by craftedsystems** [comment]
Please add this to the README. :-)

**Comment by craftedsystems** [comment]
Am I right, if I want to use a rgba value without gradient I need to set this as color.

```
rgba(147, 147, 147, 0.4);rgba(147, 147, 147, 0.4)
```
