### ISSUE TITLE
Global variables in color swatches?

### ISSUE THREAD

**Issue by virtucol** [Rias500/craft-colour-swatches#9]
What about **accepting global varibales** in the color values column?
Or is it supposed to work already, and it's just me doing something wrong?
Would be very nice and practical, feeding those fields with global color sets!

**Comment by Rias500** [comment]
This is now possible in 1.1.2, you'll have to add the reference manually though.

Example:

<img width="832" alt="afbeelding" src="https://user-images.githubusercontent.com/3626559/40300882-ce6cd50e-5cea-11e8-8fe9-55ab0fe65b7c.png">

If the fields contain a hex code or colour name they'll be displayed correctly in the field type. If you need the value in your templates you'll have to pass it though the Twig filter `|parseRefs`
